// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';

export function GetCurrentLocation():Promise<game.LocationInfo>;

export function Greet(arg1:string):Promise<string>;
