// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSave(arg1) {
  return window['go']['app']['App']['DeleteSave'](arg1);
}

export function GetAvailableConnections() {
  return window['go']['app']['App']['GetAvailableConnections']();
}

export function GetAvailableConnectionsInfo() {
  return window['go']['app']['App']['GetAvailableConnectionsInfo']();
}

export function GetCurrentLocation() {
  return window['go']['app']['App']['GetCurrentLocation']();
}

export function GetCurrentPoint() {
  return window['go']['app']['App']['GetCurrentPoint']();
}

export function GetLocationHierarchy() {
  return window['go']['app']['App']['GetLocationHierarchy']();
}

export function GetNPCsForCurrentPoint() {
  return window['go']['app']['App']['GetNPCsForCurrentPoint']();
}

export function GetSavesList() {
  return window['go']['app']['App']['GetSavesList']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function LoadGame(arg1) {
  return window['go']['app']['App']['LoadGame'](arg1);
}

export function MoveToPoint(arg1) {
  return window['go']['app']['App']['MoveToPoint'](arg1);
}

export function NewGame(arg1) {
  return window['go']['app']['App']['NewGame'](arg1);
}

export function PerformPlayerAction(arg1) {
  return window['go']['app']['App']['PerformPlayerAction'](arg1);
}

export function SaveGame(arg1) {
  return window['go']['app']['App']['SaveGame'](arg1);
}
