// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function DeleteSave(arg1:string):Promise<void>;

export function GetAvailableConnections():Promise<Array<entities.Point>>;

export function GetAvailableConnectionsInfo():Promise<Array<entities.ConnectionInfo>>;

export function GetCurrentLocation():Promise<entities.Location>;

export function GetCurrentPoint():Promise<entities.Point>;

export function GetLocationHierarchy():Promise<entities.LocationHierarchy>;

export function GetNPCsForCurrentPoint():Promise<Array<entities.NPC>>;

export function GetSavesList():Promise<Array<entities.SaveInfo>>;

export function Greet(arg1:string):Promise<string>;

export function LoadGame(arg1:string):Promise<void>;

export function MoveToPoint(arg1:string):Promise<void>;

export function NewGame(arg1:number):Promise<void>;

export function PerformPlayerAction(arg1:string):Promise<void>;

export function SaveGame(arg1:string):Promise<void>;
