// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {game} from '../models';
import {app} from '../models';

export function DeleteSave(arg1:string):Promise<void>;

export function GetCurrentLocation():Promise<game.LocationInfo>;

export function GetSavesList():Promise<Array<app.SaveInfo>>;

export function Greet(arg1:string):Promise<string>;

export function LoadGame(arg1:string):Promise<void>;

export function NewGame(arg1:number):Promise<void>;

export function SaveGame(arg1:string):Promise<void>;
